// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: src/gRPC/proto/dashboard.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DashboardService_QuantidadeProvaAluno_FullMethodName     = "/projeto.DashboardService/QuantidadeProvaAluno"
	DashboardService_QuantidadeNotaProvaAluno_FullMethodName = "/projeto.DashboardService/QuantidadeNotaProvaAluno"
	DashboardService_MediaNotaMateria_FullMethodName         = "/projeto.DashboardService/MediaNotaMateria"
	DashboardService_DistribuicaoStatusAluno_FullMethodName  = "/projeto.DashboardService/DistribuicaoStatusAluno"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	QuantidadeProvaAluno(ctx context.Context, in *QuantidadeProvaAlunoRequest, opts ...grpc.CallOption) (*QuantidadeProvaAlunoResponse, error)
	QuantidadeNotaProvaAluno(ctx context.Context, in *QuantidadeNotaProvaAlunoRequest, opts ...grpc.CallOption) (*QuantidadeNotaProvaAlunoResponse, error)
	MediaNotaMateria(ctx context.Context, in *MediaNotaMateriaRequest, opts ...grpc.CallOption) (*MediaNotaMateriaResponse, error)
	DistribuicaoStatusAluno(ctx context.Context, in *DistribuicaoStatusAlunoRequest, opts ...grpc.CallOption) (*DistribuicaoStatusAlunoResponse, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) QuantidadeProvaAluno(ctx context.Context, in *QuantidadeProvaAlunoRequest, opts ...grpc.CallOption) (*QuantidadeProvaAlunoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuantidadeProvaAlunoResponse)
	err := c.cc.Invoke(ctx, DashboardService_QuantidadeProvaAluno_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) QuantidadeNotaProvaAluno(ctx context.Context, in *QuantidadeNotaProvaAlunoRequest, opts ...grpc.CallOption) (*QuantidadeNotaProvaAlunoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuantidadeNotaProvaAlunoResponse)
	err := c.cc.Invoke(ctx, DashboardService_QuantidadeNotaProvaAluno_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) MediaNotaMateria(ctx context.Context, in *MediaNotaMateriaRequest, opts ...grpc.CallOption) (*MediaNotaMateriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MediaNotaMateriaResponse)
	err := c.cc.Invoke(ctx, DashboardService_MediaNotaMateria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) DistribuicaoStatusAluno(ctx context.Context, in *DistribuicaoStatusAlunoRequest, opts ...grpc.CallOption) (*DistribuicaoStatusAlunoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DistribuicaoStatusAlunoResponse)
	err := c.cc.Invoke(ctx, DashboardService_DistribuicaoStatusAluno_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
type DashboardServiceServer interface {
	QuantidadeProvaAluno(context.Context, *QuantidadeProvaAlunoRequest) (*QuantidadeProvaAlunoResponse, error)
	QuantidadeNotaProvaAluno(context.Context, *QuantidadeNotaProvaAlunoRequest) (*QuantidadeNotaProvaAlunoResponse, error)
	MediaNotaMateria(context.Context, *MediaNotaMateriaRequest) (*MediaNotaMateriaResponse, error)
	DistribuicaoStatusAluno(context.Context, *DistribuicaoStatusAlunoRequest) (*DistribuicaoStatusAlunoResponse, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) QuantidadeProvaAluno(context.Context, *QuantidadeProvaAlunoRequest) (*QuantidadeProvaAlunoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuantidadeProvaAluno not implemented")
}
func (UnimplementedDashboardServiceServer) QuantidadeNotaProvaAluno(context.Context, *QuantidadeNotaProvaAlunoRequest) (*QuantidadeNotaProvaAlunoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuantidadeNotaProvaAluno not implemented")
}
func (UnimplementedDashboardServiceServer) MediaNotaMateria(context.Context, *MediaNotaMateriaRequest) (*MediaNotaMateriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MediaNotaMateria not implemented")
}
func (UnimplementedDashboardServiceServer) DistribuicaoStatusAluno(context.Context, *DistribuicaoStatusAlunoRequest) (*DistribuicaoStatusAlunoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DistribuicaoStatusAluno not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call panics, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_QuantidadeProvaAluno_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuantidadeProvaAlunoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).QuantidadeProvaAluno(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_QuantidadeProvaAluno_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).QuantidadeProvaAluno(ctx, req.(*QuantidadeProvaAlunoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_QuantidadeNotaProvaAluno_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuantidadeNotaProvaAlunoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).QuantidadeNotaProvaAluno(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_QuantidadeNotaProvaAluno_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).QuantidadeNotaProvaAluno(ctx, req.(*QuantidadeNotaProvaAlunoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_MediaNotaMateria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaNotaMateriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).MediaNotaMateria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_MediaNotaMateria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).MediaNotaMateria(ctx, req.(*MediaNotaMateriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_DistribuicaoStatusAluno_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistribuicaoStatusAlunoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).DistribuicaoStatusAluno(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_DistribuicaoStatusAluno_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).DistribuicaoStatusAluno(ctx, req.(*DistribuicaoStatusAlunoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projeto.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuantidadeProvaAluno",
			Handler:    _DashboardService_QuantidadeProvaAluno_Handler,
		},
		{
			MethodName: "QuantidadeNotaProvaAluno",
			Handler:    _DashboardService_QuantidadeNotaProvaAluno_Handler,
		},
		{
			MethodName: "MediaNotaMateria",
			Handler:    _DashboardService_MediaNotaMateria_Handler,
		},
		{
			MethodName: "DistribuicaoStatusAluno",
			Handler:    _DashboardService_DistribuicaoStatusAluno_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/gRPC/proto/dashboard.proto",
}
