// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: src/gRPC/proto/dashboard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstatisticaAluno struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QuantidadeProva int64                  `protobuf:"varint,1,opt,name=quantidade_prova,json=quantidadeProva,proto3" json:"quantidade_prova,omitempty"`
	MediaProva      float32                `protobuf:"fixed32,2,opt,name=media_prova,json=mediaProva,proto3" json:"media_prova,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EstatisticaAluno) Reset() {
	*x = EstatisticaAluno{}
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstatisticaAluno) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstatisticaAluno) ProtoMessage() {}

func (x *EstatisticaAluno) ProtoReflect() protoreflect.Message {
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstatisticaAluno.ProtoReflect.Descriptor instead.
func (*EstatisticaAluno) Descriptor() ([]byte, []int) {
	return file_src_gRPC_proto_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *EstatisticaAluno) GetQuantidadeProva() int64 {
	if x != nil {
		return x.QuantidadeProva
	}
	return 0
}

func (x *EstatisticaAluno) GetMediaProva() float32 {
	if x != nil {
		return x.MediaProva
	}
	return 0
}

type QuantidadeProvaAlunoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NomeBusca     string                 `protobuf:"bytes,1,opt,name=nome_busca,json=nomeBusca,proto3" json:"nome_busca,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuantidadeProvaAlunoRequest) Reset() {
	*x = QuantidadeProvaAlunoRequest{}
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuantidadeProvaAlunoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantidadeProvaAlunoRequest) ProtoMessage() {}

func (x *QuantidadeProvaAlunoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantidadeProvaAlunoRequest.ProtoReflect.Descriptor instead.
func (*QuantidadeProvaAlunoRequest) Descriptor() ([]byte, []int) {
	return file_src_gRPC_proto_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *QuantidadeProvaAlunoRequest) GetNomeBusca() string {
	if x != nil {
		return x.NomeBusca
	}
	return ""
}

type QuantidadeProvaAlunoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      map[string]int64       `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuantidadeProvaAlunoResponse) Reset() {
	*x = QuantidadeProvaAlunoResponse{}
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuantidadeProvaAlunoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantidadeProvaAlunoResponse) ProtoMessage() {}

func (x *QuantidadeProvaAlunoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantidadeProvaAlunoResponse.ProtoReflect.Descriptor instead.
func (*QuantidadeProvaAlunoResponse) Descriptor() ([]byte, []int) {
	return file_src_gRPC_proto_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *QuantidadeProvaAlunoResponse) GetResponse() map[string]int64 {
	if x != nil {
		return x.Response
	}
	return nil
}

type QuantidadeNotaProvaAlunoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NomeBusca     string                 `protobuf:"bytes,1,opt,name=nome_busca,json=nomeBusca,proto3" json:"nome_busca,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuantidadeNotaProvaAlunoRequest) Reset() {
	*x = QuantidadeNotaProvaAlunoRequest{}
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuantidadeNotaProvaAlunoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantidadeNotaProvaAlunoRequest) ProtoMessage() {}

func (x *QuantidadeNotaProvaAlunoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantidadeNotaProvaAlunoRequest.ProtoReflect.Descriptor instead.
func (*QuantidadeNotaProvaAlunoRequest) Descriptor() ([]byte, []int) {
	return file_src_gRPC_proto_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *QuantidadeNotaProvaAlunoRequest) GetNomeBusca() string {
	if x != nil {
		return x.NomeBusca
	}
	return ""
}

type QuantidadeNotaProvaAlunoResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Response      map[string]*EstatisticaAluno `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuantidadeNotaProvaAlunoResponse) Reset() {
	*x = QuantidadeNotaProvaAlunoResponse{}
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuantidadeNotaProvaAlunoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantidadeNotaProvaAlunoResponse) ProtoMessage() {}

func (x *QuantidadeNotaProvaAlunoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantidadeNotaProvaAlunoResponse.ProtoReflect.Descriptor instead.
func (*QuantidadeNotaProvaAlunoResponse) Descriptor() ([]byte, []int) {
	return file_src_gRPC_proto_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *QuantidadeNotaProvaAlunoResponse) GetResponse() map[string]*EstatisticaAluno {
	if x != nil {
		return x.Response
	}
	return nil
}

type MediaNotaMateriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NomeCategoria string                 `protobuf:"bytes,1,opt,name=nome_categoria,json=nomeCategoria,proto3" json:"nome_categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaNotaMateriaRequest) Reset() {
	*x = MediaNotaMateriaRequest{}
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaNotaMateriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaNotaMateriaRequest) ProtoMessage() {}

func (x *MediaNotaMateriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaNotaMateriaRequest.ProtoReflect.Descriptor instead.
func (*MediaNotaMateriaRequest) Descriptor() ([]byte, []int) {
	return file_src_gRPC_proto_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *MediaNotaMateriaRequest) GetNomeCategoria() string {
	if x != nil {
		return x.NomeCategoria
	}
	return ""
}

type MediaNotaMateriaResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Response      map[string]*EstatisticaAluno `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaNotaMateriaResponse) Reset() {
	*x = MediaNotaMateriaResponse{}
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaNotaMateriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaNotaMateriaResponse) ProtoMessage() {}

func (x *MediaNotaMateriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaNotaMateriaResponse.ProtoReflect.Descriptor instead.
func (*MediaNotaMateriaResponse) Descriptor() ([]byte, []int) {
	return file_src_gRPC_proto_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *MediaNotaMateriaResponse) GetResponse() map[string]*EstatisticaAluno {
	if x != nil {
		return x.Response
	}
	return nil
}

type DistribuicaoStatusAlunoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistribuicaoStatusAlunoRequest) Reset() {
	*x = DistribuicaoStatusAlunoRequest{}
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistribuicaoStatusAlunoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistribuicaoStatusAlunoRequest) ProtoMessage() {}

func (x *DistribuicaoStatusAlunoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistribuicaoStatusAlunoRequest.ProtoReflect.Descriptor instead.
func (*DistribuicaoStatusAlunoRequest) Descriptor() ([]byte, []int) {
	return file_src_gRPC_proto_dashboard_proto_rawDescGZIP(), []int{7}
}

type DistribuicaoStatusAlunoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      map[string]int64       `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistribuicaoStatusAlunoResponse) Reset() {
	*x = DistribuicaoStatusAlunoResponse{}
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistribuicaoStatusAlunoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistribuicaoStatusAlunoResponse) ProtoMessage() {}

func (x *DistribuicaoStatusAlunoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_gRPC_proto_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistribuicaoStatusAlunoResponse.ProtoReflect.Descriptor instead.
func (*DistribuicaoStatusAlunoResponse) Descriptor() ([]byte, []int) {
	return file_src_gRPC_proto_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *DistribuicaoStatusAlunoResponse) GetResponse() map[string]int64 {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_src_gRPC_proto_dashboard_proto protoreflect.FileDescriptor

const file_src_gRPC_proto_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1esrc/gRPC/proto/dashboard.proto\x12\aprojeto\"^\n" +
	"\x10EstatisticaAluno\x12)\n" +
	"\x10quantidade_prova\x18\x01 \x01(\x03R\x0fquantidadeProva\x12\x1f\n" +
	"\vmedia_prova\x18\x02 \x01(\x02R\n" +
	"mediaProva\"<\n" +
	"\x1bQuantidadeProvaAlunoRequest\x12\x1d\n" +
	"\n" +
	"nome_busca\x18\x01 \x01(\tR\tnomeBusca\"\xac\x01\n" +
	"\x1cQuantidadeProvaAlunoResponse\x12O\n" +
	"\bresponse\x18\x01 \x03(\v23.projeto.QuantidadeProvaAlunoResponse.ResponseEntryR\bresponse\x1a;\n" +
	"\rResponseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"@\n" +
	"\x1fQuantidadeNotaProvaAlunoRequest\x12\x1d\n" +
	"\n" +
	"nome_busca\x18\x01 \x01(\tR\tnomeBusca\"\xcf\x01\n" +
	" QuantidadeNotaProvaAlunoResponse\x12S\n" +
	"\bresponse\x18\x01 \x03(\v27.projeto.QuantidadeNotaProvaAlunoResponse.ResponseEntryR\bresponse\x1aV\n" +
	"\rResponseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.projeto.EstatisticaAlunoR\x05value:\x028\x01\"@\n" +
	"\x17MediaNotaMateriaRequest\x12%\n" +
	"\x0enome_categoria\x18\x01 \x01(\tR\rnomeCategoria\"\xbf\x01\n" +
	"\x18MediaNotaMateriaResponse\x12K\n" +
	"\bresponse\x18\x01 \x03(\v2/.projeto.MediaNotaMateriaResponse.ResponseEntryR\bresponse\x1aV\n" +
	"\rResponseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.projeto.EstatisticaAlunoR\x05value:\x028\x01\" \n" +
	"\x1eDistribuicaoStatusAlunoRequest\"\xb2\x01\n" +
	"\x1fDistribuicaoStatusAlunoResponse\x12R\n" +
	"\bresponse\x18\x01 \x03(\v26.projeto.DistribuicaoStatusAlunoResponse.ResponseEntryR\bresponse\x1a;\n" +
	"\rResponseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xaf\x03\n" +
	"\x10DashboardService\x12c\n" +
	"\x14QuantidadeProvaAluno\x12$.projeto.QuantidadeProvaAlunoRequest\x1a%.projeto.QuantidadeProvaAlunoResponse\x12o\n" +
	"\x18QuantidadeNotaProvaAluno\x12(.projeto.QuantidadeNotaProvaAlunoRequest\x1a).projeto.QuantidadeNotaProvaAlunoResponse\x12W\n" +
	"\x10MediaNotaMateria\x12 .projeto.MediaNotaMateriaRequest\x1a!.projeto.MediaNotaMateriaResponse\x12l\n" +
	"\x17DistribuicaoStatusAluno\x12'.projeto.DistribuicaoStatusAlunoRequest\x1a(.projeto.DistribuicaoStatusAlunoResponseB>Z<github.com/alvarolucio2007/projeto-BD-go-3-Periodo/src/protob\x06proto3"

var (
	file_src_gRPC_proto_dashboard_proto_rawDescOnce sync.Once
	file_src_gRPC_proto_dashboard_proto_rawDescData []byte
)

func file_src_gRPC_proto_dashboard_proto_rawDescGZIP() []byte {
	file_src_gRPC_proto_dashboard_proto_rawDescOnce.Do(func() {
		file_src_gRPC_proto_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_gRPC_proto_dashboard_proto_rawDesc), len(file_src_gRPC_proto_dashboard_proto_rawDesc)))
	})
	return file_src_gRPC_proto_dashboard_proto_rawDescData
}

var file_src_gRPC_proto_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_src_gRPC_proto_dashboard_proto_goTypes = []any{
	(*EstatisticaAluno)(nil),                 // 0: projeto.EstatisticaAluno
	(*QuantidadeProvaAlunoRequest)(nil),      // 1: projeto.QuantidadeProvaAlunoRequest
	(*QuantidadeProvaAlunoResponse)(nil),     // 2: projeto.QuantidadeProvaAlunoResponse
	(*QuantidadeNotaProvaAlunoRequest)(nil),  // 3: projeto.QuantidadeNotaProvaAlunoRequest
	(*QuantidadeNotaProvaAlunoResponse)(nil), // 4: projeto.QuantidadeNotaProvaAlunoResponse
	(*MediaNotaMateriaRequest)(nil),          // 5: projeto.MediaNotaMateriaRequest
	(*MediaNotaMateriaResponse)(nil),         // 6: projeto.MediaNotaMateriaResponse
	(*DistribuicaoStatusAlunoRequest)(nil),   // 7: projeto.DistribuicaoStatusAlunoRequest
	(*DistribuicaoStatusAlunoResponse)(nil),  // 8: projeto.DistribuicaoStatusAlunoResponse
	nil,                                      // 9: projeto.QuantidadeProvaAlunoResponse.ResponseEntry
	nil,                                      // 10: projeto.QuantidadeNotaProvaAlunoResponse.ResponseEntry
	nil,                                      // 11: projeto.MediaNotaMateriaResponse.ResponseEntry
	nil,                                      // 12: projeto.DistribuicaoStatusAlunoResponse.ResponseEntry
}
var file_src_gRPC_proto_dashboard_proto_depIdxs = []int32{
	9,  // 0: projeto.QuantidadeProvaAlunoResponse.response:type_name -> projeto.QuantidadeProvaAlunoResponse.ResponseEntry
	10, // 1: projeto.QuantidadeNotaProvaAlunoResponse.response:type_name -> projeto.QuantidadeNotaProvaAlunoResponse.ResponseEntry
	11, // 2: projeto.MediaNotaMateriaResponse.response:type_name -> projeto.MediaNotaMateriaResponse.ResponseEntry
	12, // 3: projeto.DistribuicaoStatusAlunoResponse.response:type_name -> projeto.DistribuicaoStatusAlunoResponse.ResponseEntry
	0,  // 4: projeto.QuantidadeNotaProvaAlunoResponse.ResponseEntry.value:type_name -> projeto.EstatisticaAluno
	0,  // 5: projeto.MediaNotaMateriaResponse.ResponseEntry.value:type_name -> projeto.EstatisticaAluno
	1,  // 6: projeto.DashboardService.QuantidadeProvaAluno:input_type -> projeto.QuantidadeProvaAlunoRequest
	3,  // 7: projeto.DashboardService.QuantidadeNotaProvaAluno:input_type -> projeto.QuantidadeNotaProvaAlunoRequest
	5,  // 8: projeto.DashboardService.MediaNotaMateria:input_type -> projeto.MediaNotaMateriaRequest
	7,  // 9: projeto.DashboardService.DistribuicaoStatusAluno:input_type -> projeto.DistribuicaoStatusAlunoRequest
	2,  // 10: projeto.DashboardService.QuantidadeProvaAluno:output_type -> projeto.QuantidadeProvaAlunoResponse
	4,  // 11: projeto.DashboardService.QuantidadeNotaProvaAluno:output_type -> projeto.QuantidadeNotaProvaAlunoResponse
	6,  // 12: projeto.DashboardService.MediaNotaMateria:output_type -> projeto.MediaNotaMateriaResponse
	8,  // 13: projeto.DashboardService.DistribuicaoStatusAluno:output_type -> projeto.DistribuicaoStatusAlunoResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_src_gRPC_proto_dashboard_proto_init() }
func file_src_gRPC_proto_dashboard_proto_init() {
	if File_src_gRPC_proto_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_gRPC_proto_dashboard_proto_rawDesc), len(file_src_gRPC_proto_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_gRPC_proto_dashboard_proto_goTypes,
		DependencyIndexes: file_src_gRPC_proto_dashboard_proto_depIdxs,
		MessageInfos:      file_src_gRPC_proto_dashboard_proto_msgTypes,
	}.Build()
	File_src_gRPC_proto_dashboard_proto = out.File
	file_src_gRPC_proto_dashboard_proto_goTypes = nil
	file_src_gRPC_proto_dashboard_proto_depIdxs = nil
}
