// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: usuarios.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsuariosService_Create_FullMethodName  = "/projeto.UsuariosService/Create"
	UsuariosService_Read_FullMethodName    = "/projeto.UsuariosService/Read"
	UsuariosService_ReadAll_FullMethodName = "/projeto.UsuariosService/ReadAll"
	UsuariosService_Update_FullMethodName  = "/projeto.UsuariosService/Update"
	UsuariosService_Delete_FullMethodName  = "/projeto.UsuariosService/Delete"
	UsuariosService_Auth_FullMethodName    = "/projeto.UsuariosService/Auth"
)

// UsuariosServiceClient is the client API for UsuariosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsuariosServiceClient interface {
	// Criar usuário
	Create(ctx context.Context, in *UsuarioCreateRequest, opts ...grpc.CallOption) (*UsuarioCreateResponse, error)
	// Ler usuário
	Read(ctx context.Context, in *UsuarioReadRequest, opts ...grpc.CallOption) (*UsuarioReadResponse, error)
	ReadAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsuarioReadResponse, error)
	// Atualizar usuário
	Update(ctx context.Context, in *UsuarioUpdateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Deletar usuário
	Delete(ctx context.Context, in *UsuarioDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Autenticar usuário
	Auth(ctx context.Context, in *UsuarioLoginRequest, opts ...grpc.CallOption) (*UsuarioLoginResponse, error)
}

type usuariosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsuariosServiceClient(cc grpc.ClientConnInterface) UsuariosServiceClient {
	return &usuariosServiceClient{cc}
}

func (c *usuariosServiceClient) Create(ctx context.Context, in *UsuarioCreateRequest, opts ...grpc.CallOption) (*UsuarioCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsuarioCreateResponse)
	err := c.cc.Invoke(ctx, UsuariosService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosServiceClient) Read(ctx context.Context, in *UsuarioReadRequest, opts ...grpc.CallOption) (*UsuarioReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsuarioReadResponse)
	err := c.cc.Invoke(ctx, UsuariosService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosServiceClient) ReadAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsuarioReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsuarioReadResponse)
	err := c.cc.Invoke(ctx, UsuariosService_ReadAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosServiceClient) Update(ctx context.Context, in *UsuarioUpdateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UsuariosService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosServiceClient) Delete(ctx context.Context, in *UsuarioDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UsuariosService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosServiceClient) Auth(ctx context.Context, in *UsuarioLoginRequest, opts ...grpc.CallOption) (*UsuarioLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsuarioLoginResponse)
	err := c.cc.Invoke(ctx, UsuariosService_Auth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsuariosServiceServer is the server API for UsuariosService service.
// All implementations must embed UnimplementedUsuariosServiceServer
// for forward compatibility.
type UsuariosServiceServer interface {
	// Criar usuário
	Create(context.Context, *UsuarioCreateRequest) (*UsuarioCreateResponse, error)
	// Ler usuário
	Read(context.Context, *UsuarioReadRequest) (*UsuarioReadResponse, error)
	ReadAll(context.Context, *emptypb.Empty) (*UsuarioReadResponse, error)
	// Atualizar usuário
	Update(context.Context, *UsuarioUpdateRequest) (*emptypb.Empty, error)
	// Deletar usuário
	Delete(context.Context, *UsuarioDeleteRequest) (*emptypb.Empty, error)
	// Autenticar usuário
	Auth(context.Context, *UsuarioLoginRequest) (*UsuarioLoginResponse, error)
	mustEmbedUnimplementedUsuariosServiceServer()
}

// UnimplementedUsuariosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsuariosServiceServer struct{}

func (UnimplementedUsuariosServiceServer) Create(context.Context, *UsuarioCreateRequest) (*UsuarioCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUsuariosServiceServer) Read(context.Context, *UsuarioReadRequest) (*UsuarioReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedUsuariosServiceServer) ReadAll(context.Context, *emptypb.Empty) (*UsuarioReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAll not implemented")
}
func (UnimplementedUsuariosServiceServer) Update(context.Context, *UsuarioUpdateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUsuariosServiceServer) Delete(context.Context, *UsuarioDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUsuariosServiceServer) Auth(context.Context, *UsuarioLoginRequest) (*UsuarioLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedUsuariosServiceServer) mustEmbedUnimplementedUsuariosServiceServer() {}
func (UnimplementedUsuariosServiceServer) testEmbeddedByValue()                         {}

// UnsafeUsuariosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsuariosServiceServer will
// result in compilation errors.
type UnsafeUsuariosServiceServer interface {
	mustEmbedUnimplementedUsuariosServiceServer()
}

func RegisterUsuariosServiceServer(s grpc.ServiceRegistrar, srv UsuariosServiceServer) {
	// If the following call panics, it indicates UnimplementedUsuariosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsuariosService_ServiceDesc, srv)
}

func _UsuariosService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsuariosService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).Create(ctx, req.(*UsuarioCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsuariosService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsuariosService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).Read(ctx, req.(*UsuarioReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsuariosService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsuariosService_ReadAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).ReadAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsuariosService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsuariosService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).Update(ctx, req.(*UsuarioUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsuariosService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsuariosService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).Delete(ctx, req.(*UsuarioDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsuariosService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsuariosService_Auth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).Auth(ctx, req.(*UsuarioLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsuariosService_ServiceDesc is the grpc.ServiceDesc for UsuariosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsuariosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projeto.UsuariosService",
	HandlerType: (*UsuariosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UsuariosService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _UsuariosService_Read_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _UsuariosService_ReadAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UsuariosService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UsuariosService_Delete_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _UsuariosService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usuarios.proto",
}
