// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: usuarios.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// USUÁRIO
type Usuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role     string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *Usuario) Reset() {
	*x = Usuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usuarios_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usuario) ProtoMessage() {}

func (x *Usuario) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usuario.ProtoReflect.Descriptor instead.
func (*Usuario) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{0}
}

func (x *Usuario) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Usuario) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Usuario) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Usuario) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UsuarioLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UsuarioLoginRequest) Reset() {
	*x = UsuarioLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usuarios_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioLoginRequest) ProtoMessage() {}

func (x *UsuarioLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioLoginRequest.ProtoReflect.Descriptor instead.
func (*UsuarioLoginRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{1}
}

func (x *UsuarioLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsuarioLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UsuarioLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Mensagem string `protobuf:"bytes,2,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Role     string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *UsuarioLoginResponse) Reset() {
	*x = UsuarioLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usuarios_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioLoginResponse) ProtoMessage() {}

func (x *UsuarioLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioLoginResponse.ProtoReflect.Descriptor instead.
func (*UsuarioLoginResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{2}
}

func (x *UsuarioLoginResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UsuarioLoginResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *UsuarioLoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UsuarioCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role     string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *UsuarioCreateRequest) Reset() {
	*x = UsuarioCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usuarios_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioCreateRequest) ProtoMessage() {}

func (x *UsuarioCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioCreateRequest.ProtoReflect.Descriptor instead.
func (*UsuarioCreateRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{3}
}

func (x *UsuarioCreateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsuarioCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UsuarioCreateRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UsuarioCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UsuarioCreateResponse) Reset() {
	*x = UsuarioCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usuarios_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioCreateResponse) ProtoMessage() {}

func (x *UsuarioCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioCreateResponse.ProtoReflect.Descriptor instead.
func (*UsuarioCreateResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{4}
}

func (x *UsuarioCreateResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UsuarioReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
}

func (x *UsuarioReadRequest) Reset() {
	*x = UsuarioReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usuarios_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioReadRequest) ProtoMessage() {}

func (x *UsuarioReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioReadRequest.ProtoReflect.Descriptor instead.
func (*UsuarioReadRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{5}
}

func (x *UsuarioReadRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type UsuarioReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usuarios []*Usuario `protobuf:"bytes,1,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
}

func (x *UsuarioReadResponse) Reset() {
	*x = UsuarioReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usuarios_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioReadResponse) ProtoMessage() {}

func (x *UsuarioReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioReadResponse.ProtoReflect.Descriptor instead.
func (*UsuarioReadResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{6}
}

func (x *UsuarioReadResponse) GetUsuarios() []*Usuario {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

type UsuarioUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role     string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *UsuarioUpdateRequest) Reset() {
	*x = UsuarioUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usuarios_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioUpdateRequest) ProtoMessage() {}

func (x *UsuarioUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioUpdateRequest.ProtoReflect.Descriptor instead.
func (*UsuarioUpdateRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{7}
}

func (x *UsuarioUpdateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsuarioUpdateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsuarioUpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UsuarioUpdateRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UsuarioDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UsuarioDeleteRequest) Reset() {
	*x = UsuarioDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usuarios_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioDeleteRequest) ProtoMessage() {}

func (x *UsuarioDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioDeleteRequest.ProtoReflect.Descriptor instead.
func (*UsuarioDeleteRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{8}
}

func (x *UsuarioDeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_usuarios_proto protoreflect.FileDescriptor

var file_usuarios_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x07, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x4d, 0x0a,
	0x13, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5e, 0x0a, 0x14,
	0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x62, 0x0a, 0x14,
	0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x22, 0x27, 0x0a, 0x15, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x12, 0x55, 0x73, 0x75,
	0x61, 0x72, 0x69, 0x6f, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x6f, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x13, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x75, 0x73,
	0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x08,
	0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x22, 0x72, 0x0a, 0x14, 0x55, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x26, 0x0a, 0x14,
	0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x32, 0xe4, 0x02, 0x0a, 0x0f, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x75,
	0x61, 0x72, 0x69, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f,
	0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69,
	0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x43, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x76, 0x61, 0x72, 0x6f,
	0x6c, 0x75, 0x63, 0x69, 0x6f, 0x32, 0x30, 0x30, 0x37, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74,
	0x6f, 0x2d, 0x42, 0x44, 0x2d, 0x67, 0x6f, 0x2d, 0x33, 0x2d, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_usuarios_proto_rawDescOnce sync.Once
	file_usuarios_proto_rawDescData = file_usuarios_proto_rawDesc
)

func file_usuarios_proto_rawDescGZIP() []byte {
	file_usuarios_proto_rawDescOnce.Do(func() {
		file_usuarios_proto_rawDescData = protoimpl.X.CompressGZIP(file_usuarios_proto_rawDescData)
	})
	return file_usuarios_proto_rawDescData
}

var file_usuarios_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_usuarios_proto_goTypes = []interface{}{
	(*Usuario)(nil),               // 0: projeto.Usuario
	(*UsuarioLoginRequest)(nil),   // 1: projeto.UsuarioLoginRequest
	(*UsuarioLoginResponse)(nil),  // 2: projeto.UsuarioLoginResponse
	(*UsuarioCreateRequest)(nil),  // 3: projeto.UsuarioCreateRequest
	(*UsuarioCreateResponse)(nil), // 4: projeto.UsuarioCreateResponse
	(*UsuarioReadRequest)(nil),    // 5: projeto.UsuarioReadRequest
	(*UsuarioReadResponse)(nil),   // 6: projeto.UsuarioReadResponse
	(*UsuarioUpdateRequest)(nil),  // 7: projeto.UsuarioUpdateRequest
	(*UsuarioDeleteRequest)(nil),  // 8: projeto.UsuarioDeleteRequest
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_usuarios_proto_depIdxs = []int32{
	0, // 0: projeto.UsuarioReadResponse.usuarios:type_name -> projeto.Usuario
	3, // 1: projeto.UsuariosService.Create:input_type -> projeto.UsuarioCreateRequest
	5, // 2: projeto.UsuariosService.Read:input_type -> projeto.UsuarioReadRequest
	7, // 3: projeto.UsuariosService.Update:input_type -> projeto.UsuarioUpdateRequest
	8, // 4: projeto.UsuariosService.Delete:input_type -> projeto.UsuarioDeleteRequest
	1, // 5: projeto.UsuariosService.Auth:input_type -> projeto.UsuarioLoginRequest
	4, // 6: projeto.UsuariosService.Create:output_type -> projeto.UsuarioCreateResponse
	6, // 7: projeto.UsuariosService.Read:output_type -> projeto.UsuarioReadResponse
	9, // 8: projeto.UsuariosService.Update:output_type -> google.protobuf.Empty
	9, // 9: projeto.UsuariosService.Delete:output_type -> google.protobuf.Empty
	2, // 10: projeto.UsuariosService.Auth:output_type -> projeto.UsuarioLoginResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_usuarios_proto_init() }
func file_usuarios_proto_init() {
	if File_usuarios_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_usuarios_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usuarios_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsuarioLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usuarios_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsuarioLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usuarios_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsuarioCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usuarios_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsuarioCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usuarios_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsuarioReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usuarios_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsuarioReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usuarios_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsuarioUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usuarios_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsuarioDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usuarios_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usuarios_proto_goTypes,
		DependencyIndexes: file_usuarios_proto_depIdxs,
		MessageInfos:      file_usuarios_proto_msgTypes,
	}.Build()
	File_usuarios_proto = out.File
	file_usuarios_proto_rawDesc = nil
	file_usuarios_proto_goTypes = nil
	file_usuarios_proto_depIdxs = nil
}
