// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: usuarios.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// USUÁRIO
type Usuario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usuario) Reset() {
	*x = Usuario{}
	mi := &file_usuarios_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usuario) ProtoMessage() {}

func (x *Usuario) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usuario.ProtoReflect.Descriptor instead.
func (*Usuario) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{0}
}

func (x *Usuario) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Usuario) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Usuario) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Usuario) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UsuarioLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsuarioLoginRequest) Reset() {
	*x = UsuarioLoginRequest{}
	mi := &file_usuarios_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioLoginRequest) ProtoMessage() {}

func (x *UsuarioLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioLoginRequest.ProtoReflect.Descriptor instead.
func (*UsuarioLoginRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{1}
}

func (x *UsuarioLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsuarioLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UsuarioLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Mensagem      string                 `protobuf:"bytes,2,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsuarioLoginResponse) Reset() {
	*x = UsuarioLoginResponse{}
	mi := &file_usuarios_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioLoginResponse) ProtoMessage() {}

func (x *UsuarioLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioLoginResponse.ProtoReflect.Descriptor instead.
func (*UsuarioLoginResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{2}
}

func (x *UsuarioLoginResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UsuarioLoginResponse) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *UsuarioLoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UsuarioCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsuarioCreateRequest) Reset() {
	*x = UsuarioCreateRequest{}
	mi := &file_usuarios_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioCreateRequest) ProtoMessage() {}

func (x *UsuarioCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioCreateRequest.ProtoReflect.Descriptor instead.
func (*UsuarioCreateRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{3}
}

func (x *UsuarioCreateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsuarioCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UsuarioCreateRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UsuarioCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsuarioCreateResponse) Reset() {
	*x = UsuarioCreateResponse{}
	mi := &file_usuarios_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioCreateResponse) ProtoMessage() {}

func (x *UsuarioCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioCreateResponse.ProtoReflect.Descriptor instead.
func (*UsuarioCreateResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{4}
}

func (x *UsuarioCreateResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UsuarioReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsuarioReadRequest) Reset() {
	*x = UsuarioReadRequest{}
	mi := &file_usuarios_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioReadRequest) ProtoMessage() {}

func (x *UsuarioReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioReadRequest.ProtoReflect.Descriptor instead.
func (*UsuarioReadRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{5}
}

func (x *UsuarioReadRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type UsuarioReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usuarios      []*Usuario             `protobuf:"bytes,1,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsuarioReadResponse) Reset() {
	*x = UsuarioReadResponse{}
	mi := &file_usuarios_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioReadResponse) ProtoMessage() {}

func (x *UsuarioReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioReadResponse.ProtoReflect.Descriptor instead.
func (*UsuarioReadResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{6}
}

func (x *UsuarioReadResponse) GetUsuarios() []*Usuario {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

type UsuarioUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsuarioUpdateRequest) Reset() {
	*x = UsuarioUpdateRequest{}
	mi := &file_usuarios_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioUpdateRequest) ProtoMessage() {}

func (x *UsuarioUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioUpdateRequest.ProtoReflect.Descriptor instead.
func (*UsuarioUpdateRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{7}
}

func (x *UsuarioUpdateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsuarioUpdateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsuarioUpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UsuarioUpdateRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UsuarioDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsuarioDeleteRequest) Reset() {
	*x = UsuarioDeleteRequest{}
	mi := &file_usuarios_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioDeleteRequest) ProtoMessage() {}

func (x *UsuarioDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioDeleteRequest.ProtoReflect.Descriptor instead.
func (*UsuarioDeleteRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_proto_rawDescGZIP(), []int{8}
}

func (x *UsuarioDeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_usuarios_proto protoreflect.FileDescriptor

const file_usuarios_proto_rawDesc = "" +
	"\n" +
	"\x0eusuarios.proto\x12\aprojeto\x1a\x1bgoogle/protobuf/empty.proto\"e\n" +
	"\aUsuario\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"M\n" +
	"\x13UsuarioLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"^\n" +
	"\x14UsuarioLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x1a\n" +
	"\bmensagem\x18\x02 \x01(\tR\bmensagem\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"b\n" +
	"\x14UsuarioCreateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"'\n" +
	"\x15UsuarioCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"(\n" +
	"\x12UsuarioReadRequest\x12\x12\n" +
	"\x04nome\x18\x01 \x01(\tR\x04nome\"C\n" +
	"\x13UsuarioReadResponse\x12,\n" +
	"\busuarios\x18\x01 \x03(\v2\x10.projeto.UsuarioR\busuarios\"r\n" +
	"\x14UsuarioUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"&\n" +
	"\x14UsuarioDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id2\xa5\x03\n" +
	"\x0fUsuariosService\x12G\n" +
	"\x06Create\x12\x1d.projeto.UsuarioCreateRequest\x1a\x1e.projeto.UsuarioCreateResponse\x12A\n" +
	"\x04Read\x12\x1b.projeto.UsuarioReadRequest\x1a\x1c.projeto.UsuarioReadResponse\x12?\n" +
	"\aReadAll\x12\x16.google.protobuf.Empty\x1a\x1c.projeto.UsuarioReadResponse\x12?\n" +
	"\x06Update\x12\x1d.projeto.UsuarioUpdateRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x06Delete\x12\x1d.projeto.UsuarioDeleteRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x04Auth\x12\x1c.projeto.UsuarioLoginRequest\x1a\x1d.projeto.UsuarioLoginResponseB>Z<github.com/alvarolucio2007/projeto-BD-go-3-Periodo/src/protob\x06proto3"

var (
	file_usuarios_proto_rawDescOnce sync.Once
	file_usuarios_proto_rawDescData []byte
)

func file_usuarios_proto_rawDescGZIP() []byte {
	file_usuarios_proto_rawDescOnce.Do(func() {
		file_usuarios_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usuarios_proto_rawDesc), len(file_usuarios_proto_rawDesc)))
	})
	return file_usuarios_proto_rawDescData
}

var file_usuarios_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_usuarios_proto_goTypes = []any{
	(*Usuario)(nil),               // 0: projeto.Usuario
	(*UsuarioLoginRequest)(nil),   // 1: projeto.UsuarioLoginRequest
	(*UsuarioLoginResponse)(nil),  // 2: projeto.UsuarioLoginResponse
	(*UsuarioCreateRequest)(nil),  // 3: projeto.UsuarioCreateRequest
	(*UsuarioCreateResponse)(nil), // 4: projeto.UsuarioCreateResponse
	(*UsuarioReadRequest)(nil),    // 5: projeto.UsuarioReadRequest
	(*UsuarioReadResponse)(nil),   // 6: projeto.UsuarioReadResponse
	(*UsuarioUpdateRequest)(nil),  // 7: projeto.UsuarioUpdateRequest
	(*UsuarioDeleteRequest)(nil),  // 8: projeto.UsuarioDeleteRequest
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_usuarios_proto_depIdxs = []int32{
	0, // 0: projeto.UsuarioReadResponse.usuarios:type_name -> projeto.Usuario
	3, // 1: projeto.UsuariosService.Create:input_type -> projeto.UsuarioCreateRequest
	5, // 2: projeto.UsuariosService.Read:input_type -> projeto.UsuarioReadRequest
	9, // 3: projeto.UsuariosService.ReadAll:input_type -> google.protobuf.Empty
	7, // 4: projeto.UsuariosService.Update:input_type -> projeto.UsuarioUpdateRequest
	8, // 5: projeto.UsuariosService.Delete:input_type -> projeto.UsuarioDeleteRequest
	1, // 6: projeto.UsuariosService.Auth:input_type -> projeto.UsuarioLoginRequest
	4, // 7: projeto.UsuariosService.Create:output_type -> projeto.UsuarioCreateResponse
	6, // 8: projeto.UsuariosService.Read:output_type -> projeto.UsuarioReadResponse
	6, // 9: projeto.UsuariosService.ReadAll:output_type -> projeto.UsuarioReadResponse
	9, // 10: projeto.UsuariosService.Update:output_type -> google.protobuf.Empty
	9, // 11: projeto.UsuariosService.Delete:output_type -> google.protobuf.Empty
	2, // 12: projeto.UsuariosService.Auth:output_type -> projeto.UsuarioLoginResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_usuarios_proto_init() }
func file_usuarios_proto_init() {
	if File_usuarios_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usuarios_proto_rawDesc), len(file_usuarios_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usuarios_proto_goTypes,
		DependencyIndexes: file_usuarios_proto_depIdxs,
		MessageInfos:      file_usuarios_proto_msgTypes,
	}.Build()
	File_usuarios_proto = out.File
	file_usuarios_proto_goTypes = nil
	file_usuarios_proto_depIdxs = nil
}
