// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// InnerJoinServiceClient is the client API for InnerJoinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InnerJoinServiceClient interface {
	InnerJoin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InnerJoinResponse, error)
}

type innerJoinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInnerJoinServiceClient(cc grpc.ClientConnInterface) InnerJoinServiceClient {
	return &innerJoinServiceClient{cc}
}

func (c *innerJoinServiceClient) InnerJoin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InnerJoinResponse, error) {
	out := new(InnerJoinResponse)
	err := c.cc.Invoke(ctx, "/projeto.InnerJoinService/InnerJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnerJoinServiceServer is the server API for InnerJoinService service.
// All implementations must embed UnimplementedInnerJoinServiceServer
// for forward compatibility
type InnerJoinServiceServer interface {
	InnerJoin(context.Context, *emptypb.Empty) (*InnerJoinResponse, error)
	mustEmbedUnimplementedInnerJoinServiceServer()
}

// UnimplementedInnerJoinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInnerJoinServiceServer struct {
}

func (UnimplementedInnerJoinServiceServer) InnerJoin(context.Context, *emptypb.Empty) (*InnerJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InnerJoin not implemented")
}
func (UnimplementedInnerJoinServiceServer) mustEmbedUnimplementedInnerJoinServiceServer() {}

// UnsafeInnerJoinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InnerJoinServiceServer will
// result in compilation errors.
type UnsafeInnerJoinServiceServer interface {
	mustEmbedUnimplementedInnerJoinServiceServer()
}

func RegisterInnerJoinServiceServer(s *grpc.Server, srv InnerJoinServiceServer) {
	s.RegisterService(&_InnerJoinService_serviceDesc, srv)
}

func _InnerJoinService_InnerJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerJoinServiceServer).InnerJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.InnerJoinService/InnerJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerJoinServiceServer).InnerJoin(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _InnerJoinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projeto.InnerJoinService",
	HandlerType: (*InnerJoinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InnerJoin",
			Handler:    _InnerJoinService_InnerJoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inner_join.proto",
}
