// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// InnerJoinServiceClient is the client API for InnerJoinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InnerJoinServiceClient interface {
	InnerJoin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (InnerJoinService_InnerJoinClient, error)
}

type innerJoinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInnerJoinServiceClient(cc grpc.ClientConnInterface) InnerJoinServiceClient {
	return &innerJoinServiceClient{cc}
}

func (c *innerJoinServiceClient) InnerJoin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (InnerJoinService_InnerJoinClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InnerJoinService_serviceDesc.Streams[0], "/projeto.InnerJoinService/InnerJoin", opts...)
	if err != nil {
		return nil, err
	}
	x := &innerJoinServiceInnerJoinClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InnerJoinService_InnerJoinClient interface {
	Recv() (*InnerJoinResponse, error)
	grpc.ClientStream
}

type innerJoinServiceInnerJoinClient struct {
	grpc.ClientStream
}

func (x *innerJoinServiceInnerJoinClient) Recv() (*InnerJoinResponse, error) {
	m := new(InnerJoinResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InnerJoinServiceServer is the server API for InnerJoinService service.
// All implementations must embed UnimplementedInnerJoinServiceServer
// for forward compatibility
type InnerJoinServiceServer interface {
	InnerJoin(*emptypb.Empty, InnerJoinService_InnerJoinServer) error
	mustEmbedUnimplementedInnerJoinServiceServer()
}

// UnimplementedInnerJoinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInnerJoinServiceServer struct {
}

func (UnimplementedInnerJoinServiceServer) InnerJoin(*emptypb.Empty, InnerJoinService_InnerJoinServer) error {
	return status.Errorf(codes.Unimplemented, "method InnerJoin not implemented")
}
func (UnimplementedInnerJoinServiceServer) mustEmbedUnimplementedInnerJoinServiceServer() {}

// UnsafeInnerJoinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InnerJoinServiceServer will
// result in compilation errors.
type UnsafeInnerJoinServiceServer interface {
	mustEmbedUnimplementedInnerJoinServiceServer()
}

func RegisterInnerJoinServiceServer(s *grpc.Server, srv InnerJoinServiceServer) {
	s.RegisterService(&_InnerJoinService_serviceDesc, srv)
}

func _InnerJoinService_InnerJoin_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InnerJoinServiceServer).InnerJoin(m, &innerJoinServiceInnerJoinServer{stream})
}

type InnerJoinService_InnerJoinServer interface {
	Send(*InnerJoinResponse) error
	grpc.ServerStream
}

type innerJoinServiceInnerJoinServer struct {
	grpc.ServerStream
}

func (x *innerJoinServiceInnerJoinServer) Send(m *InnerJoinResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _InnerJoinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projeto.InnerJoinService",
	HandlerType: (*InnerJoinServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InnerJoin",
			Handler:       _InnerJoinService_InnerJoin_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inner_join.proto",
}
