// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// LeftJoinServiceClient is the client API for LeftJoinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeftJoinServiceClient interface {
	LeftJoin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LeftJoinResponse, error)
}

type leftJoinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeftJoinServiceClient(cc grpc.ClientConnInterface) LeftJoinServiceClient {
	return &leftJoinServiceClient{cc}
}

func (c *leftJoinServiceClient) LeftJoin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LeftJoinResponse, error) {
	out := new(LeftJoinResponse)
	err := c.cc.Invoke(ctx, "/projeto.LeftJoinService/LeftJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeftJoinServiceServer is the server API for LeftJoinService service.
// All implementations must embed UnimplementedLeftJoinServiceServer
// for forward compatibility
type LeftJoinServiceServer interface {
	LeftJoin(context.Context, *emptypb.Empty) (*LeftJoinResponse, error)
	mustEmbedUnimplementedLeftJoinServiceServer()
}

// UnimplementedLeftJoinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLeftJoinServiceServer struct {
}

func (UnimplementedLeftJoinServiceServer) LeftJoin(context.Context, *emptypb.Empty) (*LeftJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeftJoin not implemented")
}
func (UnimplementedLeftJoinServiceServer) mustEmbedUnimplementedLeftJoinServiceServer() {}

// UnsafeLeftJoinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeftJoinServiceServer will
// result in compilation errors.
type UnsafeLeftJoinServiceServer interface {
	mustEmbedUnimplementedLeftJoinServiceServer()
}

func RegisterLeftJoinServiceServer(s *grpc.Server, srv LeftJoinServiceServer) {
	s.RegisterService(&_LeftJoinService_serviceDesc, srv)
}

func _LeftJoinService_LeftJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeftJoinServiceServer).LeftJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.LeftJoinService/LeftJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeftJoinServiceServer).LeftJoin(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeftJoinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projeto.LeftJoinService",
	HandlerType: (*LeftJoinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LeftJoin",
			Handler:    _LeftJoinService_LeftJoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "left_join.proto",
}
