// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// LeftJoinServiceClient is the client API for LeftJoinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeftJoinServiceClient interface {
	LeftJoin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (LeftJoinService_LeftJoinClient, error)
}

type leftJoinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeftJoinServiceClient(cc grpc.ClientConnInterface) LeftJoinServiceClient {
	return &leftJoinServiceClient{cc}
}

func (c *leftJoinServiceClient) LeftJoin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (LeftJoinService_LeftJoinClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LeftJoinService_serviceDesc.Streams[0], "/projeto.LeftJoinService/LeftJoin", opts...)
	if err != nil {
		return nil, err
	}
	x := &leftJoinServiceLeftJoinClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LeftJoinService_LeftJoinClient interface {
	Recv() (*LeftJoinResponse, error)
	grpc.ClientStream
}

type leftJoinServiceLeftJoinClient struct {
	grpc.ClientStream
}

func (x *leftJoinServiceLeftJoinClient) Recv() (*LeftJoinResponse, error) {
	m := new(LeftJoinResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LeftJoinServiceServer is the server API for LeftJoinService service.
// All implementations must embed UnimplementedLeftJoinServiceServer
// for forward compatibility
type LeftJoinServiceServer interface {
	LeftJoin(*emptypb.Empty, LeftJoinService_LeftJoinServer) error
	mustEmbedUnimplementedLeftJoinServiceServer()
}

// UnimplementedLeftJoinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLeftJoinServiceServer struct {
}

func (UnimplementedLeftJoinServiceServer) LeftJoin(*emptypb.Empty, LeftJoinService_LeftJoinServer) error {
	return status.Errorf(codes.Unimplemented, "method LeftJoin not implemented")
}
func (UnimplementedLeftJoinServiceServer) mustEmbedUnimplementedLeftJoinServiceServer() {}

// UnsafeLeftJoinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeftJoinServiceServer will
// result in compilation errors.
type UnsafeLeftJoinServiceServer interface {
	mustEmbedUnimplementedLeftJoinServiceServer()
}

func RegisterLeftJoinServiceServer(s *grpc.Server, srv LeftJoinServiceServer) {
	s.RegisterService(&_LeftJoinService_serviceDesc, srv)
}

func _LeftJoinService_LeftJoin_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LeftJoinServiceServer).LeftJoin(m, &leftJoinServiceLeftJoinServer{stream})
}

type LeftJoinService_LeftJoinServer interface {
	Send(*LeftJoinResponse) error
	grpc.ServerStream
}

type leftJoinServiceLeftJoinServer struct {
	grpc.ServerStream
}

func (x *leftJoinServiceLeftJoinServer) Send(m *LeftJoinResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _LeftJoinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projeto.LeftJoinService",
	HandlerType: (*LeftJoinServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LeftJoin",
			Handler:       _LeftJoinService_LeftJoin_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "left_join.proto",
}
