// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// NotaServiceClient is the client API for NotaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotaServiceClient interface {
	Create(ctx context.Context, in *CreateNotaRequest, opts ...grpc.CallOption) (*CreateNotaResponse, error)
	Read(ctx context.Context, in *ReadNotaRequest, opts ...grpc.CallOption) (*NotasResponse, error)
	Update(ctx context.Context, in *UpdateNotaRequest, opts ...grpc.CallOption) (*Nota, error)
	Delete(ctx context.Context, in *DeleteNotaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type notaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotaServiceClient(cc grpc.ClientConnInterface) NotaServiceClient {
	return &notaServiceClient{cc}
}

func (c *notaServiceClient) Create(ctx context.Context, in *CreateNotaRequest, opts ...grpc.CallOption) (*CreateNotaResponse, error) {
	out := new(CreateNotaResponse)
	err := c.cc.Invoke(ctx, "/projeto.NotaService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaServiceClient) Read(ctx context.Context, in *ReadNotaRequest, opts ...grpc.CallOption) (*NotasResponse, error) {
	out := new(NotasResponse)
	err := c.cc.Invoke(ctx, "/projeto.NotaService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaServiceClient) Update(ctx context.Context, in *UpdateNotaRequest, opts ...grpc.CallOption) (*Nota, error) {
	out := new(Nota)
	err := c.cc.Invoke(ctx, "/projeto.NotaService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaServiceClient) Delete(ctx context.Context, in *DeleteNotaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/projeto.NotaService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotaServiceServer is the server API for NotaService service.
// All implementations must embed UnimplementedNotaServiceServer
// for forward compatibility
type NotaServiceServer interface {
	Create(context.Context, *CreateNotaRequest) (*CreateNotaResponse, error)
	Read(context.Context, *ReadNotaRequest) (*NotasResponse, error)
	Update(context.Context, *UpdateNotaRequest) (*Nota, error)
	Delete(context.Context, *DeleteNotaRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedNotaServiceServer()
}

// UnimplementedNotaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotaServiceServer struct {
}

func (UnimplementedNotaServiceServer) Create(context.Context, *CreateNotaRequest) (*CreateNotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedNotaServiceServer) Read(context.Context, *ReadNotaRequest) (*NotasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedNotaServiceServer) Update(context.Context, *UpdateNotaRequest) (*Nota, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedNotaServiceServer) Delete(context.Context, *DeleteNotaRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedNotaServiceServer) mustEmbedUnimplementedNotaServiceServer() {}

// UnsafeNotaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotaServiceServer will
// result in compilation errors.
type UnsafeNotaServiceServer interface {
	mustEmbedUnimplementedNotaServiceServer()
}

func RegisterNotaServiceServer(s *grpc.Server, srv NotaServiceServer) {
	s.RegisterService(&_NotaService_serviceDesc, srv)
}

func _NotaService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.NotaService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaServiceServer).Create(ctx, req.(*CreateNotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotaService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.NotaService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaServiceServer).Read(ctx, req.(*ReadNotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotaService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.NotaService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaServiceServer).Update(ctx, req.(*UpdateNotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotaService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.NotaService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaServiceServer).Delete(ctx, req.(*DeleteNotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projeto.NotaService",
	HandlerType: (*NotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NotaService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _NotaService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _NotaService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NotaService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notas.proto",
}
