// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: notas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nota struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotaId    uint32   `protobuf:"varint,1,opt,name=nota_id,json=notaId,proto3" json:"nota_id,omitempty"`
	ValorNota float32  `protobuf:"fixed32,2,opt,name=valor_nota,json=valorNota,proto3" json:"valor_nota,omitempty"`
	Aluno     *Usuario `protobuf:"bytes,3,opt,name=aluno,proto3" json:"aluno,omitempty"`
	Prova     *Prova   `protobuf:"bytes,4,opt,name=prova,proto3" json:"prova,omitempty"`
}

func (x *Nota) Reset() {
	*x = Nota{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nota) ProtoMessage() {}

func (x *Nota) ProtoReflect() protoreflect.Message {
	mi := &file_notas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nota.ProtoReflect.Descriptor instead.
func (*Nota) Descriptor() ([]byte, []int) {
	return file_notas_proto_rawDescGZIP(), []int{0}
}

func (x *Nota) GetNotaId() uint32 {
	if x != nil {
		return x.NotaId
	}
	return 0
}

func (x *Nota) GetValorNota() float32 {
	if x != nil {
		return x.ValorNota
	}
	return 0
}

func (x *Nota) GetAluno() *Usuario {
	if x != nil {
		return x.Aluno
	}
	return nil
}

func (x *Nota) GetProva() *Prova {
	if x != nil {
		return x.Prova
	}
	return nil
}

type CreateNotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsuarioId uint32  `protobuf:"varint,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	ProvaId   uint32  `protobuf:"varint,2,opt,name=prova_id,json=provaId,proto3" json:"prova_id,omitempty"`
	NotaProva float32 `protobuf:"fixed32,3,opt,name=nota_prova,json=notaProva,proto3" json:"nota_prova,omitempty"`
}

func (x *CreateNotaRequest) Reset() {
	*x = CreateNotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotaRequest) ProtoMessage() {}

func (x *CreateNotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotaRequest.ProtoReflect.Descriptor instead.
func (*CreateNotaRequest) Descriptor() ([]byte, []int) {
	return file_notas_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNotaRequest) GetUsuarioId() uint32 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

func (x *CreateNotaRequest) GetProvaId() uint32 {
	if x != nil {
		return x.ProvaId
	}
	return 0
}

func (x *CreateNotaRequest) GetNotaProva() float32 {
	if x != nil {
		return x.NotaProva
	}
	return 0
}

type CreateNotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotaId uint32 `protobuf:"varint,1,opt,name=nota_id,json=notaId,proto3" json:"nota_id,omitempty"`
}

func (x *CreateNotaResponse) Reset() {
	*x = CreateNotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotaResponse) ProtoMessage() {}

func (x *CreateNotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotaResponse.ProtoReflect.Descriptor instead.
func (*CreateNotaResponse) Descriptor() ([]byte, []int) {
	return file_notas_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotaResponse) GetNotaId() uint32 {
	if x != nil {
		return x.NotaId
	}
	return 0
}

type ReadNotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ReadNotaRequest) Reset() {
	*x = ReadNotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNotaRequest) ProtoMessage() {}

func (x *ReadNotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNotaRequest.ProtoReflect.Descriptor instead.
func (*ReadNotaRequest) Descriptor() ([]byte, []int) {
	return file_notas_proto_rawDescGZIP(), []int{3}
}

func (x *ReadNotaRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type NotasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*NotaDetalhada `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *NotasResponse) Reset() {
	*x = NotasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notas_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotasResponse) ProtoMessage() {}

func (x *NotasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notas_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotasResponse.ProtoReflect.Descriptor instead.
func (*NotasResponse) Descriptor() ([]byte, []int) {
	return file_notas_proto_rawDescGZIP(), []int{4}
}

func (x *NotasResponse) GetResponse() []*NotaDetalhada {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateNotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotaId    uint32  `protobuf:"varint,1,opt,name=nota_id,json=notaId,proto3" json:"nota_id,omitempty"`
	ValorNota float32 `protobuf:"fixed32,2,opt,name=valor_nota,json=valorNota,proto3" json:"valor_nota,omitempty"`
	AlunoId   uint32  `protobuf:"varint,3,opt,name=aluno_id,json=alunoId,proto3" json:"aluno_id,omitempty"`
	ProvaId   uint32  `protobuf:"varint,4,opt,name=prova_id,json=provaId,proto3" json:"prova_id,omitempty"`
}

func (x *UpdateNotaRequest) Reset() {
	*x = UpdateNotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notas_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotaRequest) ProtoMessage() {}

func (x *UpdateNotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notas_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotaRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotaRequest) Descriptor() ([]byte, []int) {
	return file_notas_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNotaRequest) GetNotaId() uint32 {
	if x != nil {
		return x.NotaId
	}
	return 0
}

func (x *UpdateNotaRequest) GetValorNota() float32 {
	if x != nil {
		return x.ValorNota
	}
	return 0
}

func (x *UpdateNotaRequest) GetAlunoId() uint32 {
	if x != nil {
		return x.AlunoId
	}
	return 0
}

func (x *UpdateNotaRequest) GetProvaId() uint32 {
	if x != nil {
		return x.ProvaId
	}
	return 0
}

type DeleteNotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotaId uint32 `protobuf:"varint,1,opt,name=nota_id,json=notaId,proto3" json:"nota_id,omitempty"`
}

func (x *DeleteNotaRequest) Reset() {
	*x = DeleteNotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notas_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotaRequest) ProtoMessage() {}

func (x *DeleteNotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notas_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotaRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotaRequest) Descriptor() ([]byte, []int) {
	return file_notas_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNotaRequest) GetNotaId() uint32 {
	if x != nil {
		return x.NotaId
	}
	return 0
}

var File_notas_proto protoreflect.FileDescriptor

var file_notas_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6e, 0x6f, 0x74, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e,
	0x6f, 0x74, 0x61, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x5f, 0x6e,
	0x6f, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x6f, 0x72,
	0x4e, 0x6f, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x05, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x55, 0x73,
	0x75, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x05, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x12, 0x24, 0x0a, 0x05,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x52, 0x05, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x22, 0x6c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x73, 0x75,
	0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x61,
	0x22, 0x2d, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x61, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x61, 0x49, 0x64, 0x22,
	0x2d, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x43,
	0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x61,
	0x44, 0x65, 0x74, 0x61, 0x6c, 0x68, 0x61, 0x64, 0x61, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74,
	0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x61,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x4e, 0x6f, 0x74,
	0x61, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e,
	0x6f, 0x74, 0x61, 0x49, 0x64, 0x32, 0x86, 0x02, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x61, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64,
	0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4e,
	0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x3c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x3e,
	0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x76,
	0x61, 0x72, 0x6f, 0x6c, 0x75, 0x63, 0x69, 0x6f, 0x32, 0x30, 0x30, 0x37, 0x2f, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x74, 0x6f, 0x2d, 0x42, 0x44, 0x2d, 0x67, 0x6f, 0x2d, 0x33, 0x2d, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notas_proto_rawDescOnce sync.Once
	file_notas_proto_rawDescData = file_notas_proto_rawDesc
)

func file_notas_proto_rawDescGZIP() []byte {
	file_notas_proto_rawDescOnce.Do(func() {
		file_notas_proto_rawDescData = protoimpl.X.CompressGZIP(file_notas_proto_rawDescData)
	})
	return file_notas_proto_rawDescData
}

var file_notas_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_notas_proto_goTypes = []interface{}{
	(*Nota)(nil),               // 0: projeto.Nota
	(*CreateNotaRequest)(nil),  // 1: projeto.CreateNotaRequest
	(*CreateNotaResponse)(nil), // 2: projeto.CreateNotaResponse
	(*ReadNotaRequest)(nil),    // 3: projeto.ReadNotaRequest
	(*NotasResponse)(nil),      // 4: projeto.NotasResponse
	(*UpdateNotaRequest)(nil),  // 5: projeto.UpdateNotaRequest
	(*DeleteNotaRequest)(nil),  // 6: projeto.DeleteNotaRequest
	(*Usuario)(nil),            // 7: projeto.Usuario
	(*Prova)(nil),              // 8: projeto.Prova
	(*NotaDetalhada)(nil),      // 9: projeto.NotaDetalhada
	(*emptypb.Empty)(nil),      // 10: google.protobuf.Empty
}
var file_notas_proto_depIdxs = []int32{
	7,  // 0: projeto.Nota.aluno:type_name -> projeto.Usuario
	8,  // 1: projeto.Nota.prova:type_name -> projeto.Prova
	9,  // 2: projeto.NotasResponse.response:type_name -> projeto.NotaDetalhada
	1,  // 3: projeto.NotaService.Create:input_type -> projeto.CreateNotaRequest
	3,  // 4: projeto.NotaService.Read:input_type -> projeto.ReadNotaRequest
	5,  // 5: projeto.NotaService.Update:input_type -> projeto.UpdateNotaRequest
	6,  // 6: projeto.NotaService.Delete:input_type -> projeto.DeleteNotaRequest
	2,  // 7: projeto.NotaService.Create:output_type -> projeto.CreateNotaResponse
	4,  // 8: projeto.NotaService.Read:output_type -> projeto.NotasResponse
	10, // 9: projeto.NotaService.Update:output_type -> google.protobuf.Empty
	10, // 10: projeto.NotaService.Delete:output_type -> google.protobuf.Empty
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_notas_proto_init() }
func file_notas_proto_init() {
	if File_notas_proto != nil {
		return
	}
	file_inner_join_proto_init()
	file_provas_proto_init()
	file_usuarios_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_notas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nota); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notas_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notas_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notas_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notas_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notas_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notas_proto_goTypes,
		DependencyIndexes: file_notas_proto_depIdxs,
		MessageInfos:      file_notas_proto_msgTypes,
	}.Build()
	File_notas_proto = out.File
	file_notas_proto_rawDesc = nil
	file_notas_proto_goTypes = nil
	file_notas_proto_depIdxs = nil
}
