// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ProvaServiceClient is the client API for ProvaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvaServiceClient interface {
	// Criar prova
	Create(ctx context.Context, in *CreateProvaRequest, opts ...grpc.CallOption) (*CreateProvaResponse, error)
	// Ler prova (tanto pesquisar quanto listar todas)
	ReadAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProvaLista, error)
	Read(ctx context.Context, in *ReadProvaRequest, opts ...grpc.CallOption) (*ProvaLista, error)
	// Atualizar prova
	Update(ctx context.Context, in *UpdateProvaRequest, opts ...grpc.CallOption) (*Prova, error)
	// Deletar prova
	Delete(ctx context.Context, in *DeleteProvaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type provaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvaServiceClient(cc grpc.ClientConnInterface) ProvaServiceClient {
	return &provaServiceClient{cc}
}

func (c *provaServiceClient) Create(ctx context.Context, in *CreateProvaRequest, opts ...grpc.CallOption) (*CreateProvaResponse, error) {
	out := new(CreateProvaResponse)
	err := c.cc.Invoke(ctx, "/projeto.ProvaService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provaServiceClient) ReadAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProvaLista, error) {
	out := new(ProvaLista)
	err := c.cc.Invoke(ctx, "/projeto.ProvaService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provaServiceClient) Read(ctx context.Context, in *ReadProvaRequest, opts ...grpc.CallOption) (*ProvaLista, error) {
	out := new(ProvaLista)
	err := c.cc.Invoke(ctx, "/projeto.ProvaService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provaServiceClient) Update(ctx context.Context, in *UpdateProvaRequest, opts ...grpc.CallOption) (*Prova, error) {
	out := new(Prova)
	err := c.cc.Invoke(ctx, "/projeto.ProvaService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provaServiceClient) Delete(ctx context.Context, in *DeleteProvaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/projeto.ProvaService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvaServiceServer is the server API for ProvaService service.
// All implementations must embed UnimplementedProvaServiceServer
// for forward compatibility
type ProvaServiceServer interface {
	// Criar prova
	Create(context.Context, *CreateProvaRequest) (*CreateProvaResponse, error)
	// Ler prova (tanto pesquisar quanto listar todas)
	ReadAll(context.Context, *emptypb.Empty) (*ProvaLista, error)
	Read(context.Context, *ReadProvaRequest) (*ProvaLista, error)
	// Atualizar prova
	Update(context.Context, *UpdateProvaRequest) (*Prova, error)
	// Deletar prova
	Delete(context.Context, *DeleteProvaRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedProvaServiceServer()
}

// UnimplementedProvaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProvaServiceServer struct {
}

func (UnimplementedProvaServiceServer) Create(context.Context, *CreateProvaRequest) (*CreateProvaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProvaServiceServer) ReadAll(context.Context, *emptypb.Empty) (*ProvaLista, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAll not implemented")
}
func (UnimplementedProvaServiceServer) Read(context.Context, *ReadProvaRequest) (*ProvaLista, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedProvaServiceServer) Update(context.Context, *UpdateProvaRequest) (*Prova, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProvaServiceServer) Delete(context.Context, *DeleteProvaRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProvaServiceServer) mustEmbedUnimplementedProvaServiceServer() {}

// UnsafeProvaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvaServiceServer will
// result in compilation errors.
type UnsafeProvaServiceServer interface {
	mustEmbedUnimplementedProvaServiceServer()
}

func RegisterProvaServiceServer(s *grpc.Server, srv ProvaServiceServer) {
	s.RegisterService(&_ProvaService_serviceDesc, srv)
}

func _ProvaService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProvaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvaServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.ProvaService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvaServiceServer).Create(ctx, req.(*CreateProvaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvaService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvaServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.ProvaService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvaServiceServer).ReadAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvaService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProvaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvaServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.ProvaService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvaServiceServer).Read(ctx, req.(*ReadProvaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvaService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProvaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvaServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.ProvaService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvaServiceServer).Update(ctx, req.(*UpdateProvaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvaService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProvaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvaServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.ProvaService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvaServiceServer).Delete(ctx, req.(*DeleteProvaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProvaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projeto.ProvaService",
	HandlerType: (*ProvaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProvaService_Create_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _ProvaService_ReadAll_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ProvaService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProvaService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProvaService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provas.proto",
}
