// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: provas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PROVA
type Prova struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NomeProva    string                 `protobuf:"bytes,2,opt,name=nome_prova,json=nomeProva,proto3" json:"nome_prova,omitempty"`
	TurmaProva   string                 `protobuf:"bytes,3,opt,name=turma_prova,json=turmaProva,proto3" json:"turma_prova,omitempty"`
	MateriaProva string                 `protobuf:"bytes,4,opt,name=materia_prova,json=materiaProva,proto3" json:"materia_prova,omitempty"`
	DataProva    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=data_prova,json=dataProva,proto3" json:"data_prova,omitempty"`
}

func (x *Prova) Reset() {
	*x = Prova{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prova) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prova) ProtoMessage() {}

func (x *Prova) ProtoReflect() protoreflect.Message {
	mi := &file_provas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prova.ProtoReflect.Descriptor instead.
func (*Prova) Descriptor() ([]byte, []int) {
	return file_provas_proto_rawDescGZIP(), []int{0}
}

func (x *Prova) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Prova) GetNomeProva() string {
	if x != nil {
		return x.NomeProva
	}
	return ""
}

func (x *Prova) GetTurmaProva() string {
	if x != nil {
		return x.TurmaProva
	}
	return ""
}

func (x *Prova) GetMateriaProva() string {
	if x != nil {
		return x.MateriaProva
	}
	return ""
}

func (x *Prova) GetDataProva() *timestamppb.Timestamp {
	if x != nil {
		return x.DataProva
	}
	return nil
}

type ProvaLista struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProvaLista []*Prova `protobuf:"bytes,1,rep,name=prova_lista,json=provaLista,proto3" json:"prova_lista,omitempty"`
}

func (x *ProvaLista) Reset() {
	*x = ProvaLista{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvaLista) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvaLista) ProtoMessage() {}

func (x *ProvaLista) ProtoReflect() protoreflect.Message {
	mi := &file_provas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvaLista.ProtoReflect.Descriptor instead.
func (*ProvaLista) Descriptor() ([]byte, []int) {
	return file_provas_proto_rawDescGZIP(), []int{1}
}

func (x *ProvaLista) GetProvaLista() []*Prova {
	if x != nil {
		return x.ProvaLista
	}
	return nil
}

type CreateProvaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NomeProva    string                 `protobuf:"bytes,1,opt,name=nome_prova,json=nomeProva,proto3" json:"nome_prova,omitempty"`
	TurmaProva   string                 `protobuf:"bytes,2,opt,name=turma_prova,json=turmaProva,proto3" json:"turma_prova,omitempty"`
	MateriaProva string                 `protobuf:"bytes,3,opt,name=materia_prova,json=materiaProva,proto3" json:"materia_prova,omitempty"`
	DataProva    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=data_prova,json=dataProva,proto3" json:"data_prova,omitempty"`
}

func (x *CreateProvaRequest) Reset() {
	*x = CreateProvaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProvaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProvaRequest) ProtoMessage() {}

func (x *CreateProvaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProvaRequest.ProtoReflect.Descriptor instead.
func (*CreateProvaRequest) Descriptor() ([]byte, []int) {
	return file_provas_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProvaRequest) GetNomeProva() string {
	if x != nil {
		return x.NomeProva
	}
	return ""
}

func (x *CreateProvaRequest) GetTurmaProva() string {
	if x != nil {
		return x.TurmaProva
	}
	return ""
}

func (x *CreateProvaRequest) GetMateriaProva() string {
	if x != nil {
		return x.MateriaProva
	}
	return ""
}

func (x *CreateProvaRequest) GetDataProva() *timestamppb.Timestamp {
	if x != nil {
		return x.DataProva
	}
	return nil
}

type CreateProvaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdProva uint32 `protobuf:"varint,1,opt,name=id_prova,json=idProva,proto3" json:"id_prova,omitempty"`
}

func (x *CreateProvaResponse) Reset() {
	*x = CreateProvaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProvaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProvaResponse) ProtoMessage() {}

func (x *CreateProvaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProvaResponse.ProtoReflect.Descriptor instead.
func (*CreateProvaResponse) Descriptor() ([]byte, []int) {
	return file_provas_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProvaResponse) GetIdProva() uint32 {
	if x != nil {
		return x.IdProva
	}
	return 0
}

type ReadProvaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NomeProva string `protobuf:"bytes,1,opt,name=nome_prova,json=nomeProva,proto3" json:"nome_prova,omitempty"`
	IdUsuario uint32 `protobuf:"varint,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
}

func (x *ReadProvaRequest) Reset() {
	*x = ReadProvaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provas_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadProvaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadProvaRequest) ProtoMessage() {}

func (x *ReadProvaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provas_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadProvaRequest.ProtoReflect.Descriptor instead.
func (*ReadProvaRequest) Descriptor() ([]byte, []int) {
	return file_provas_proto_rawDescGZIP(), []int{4}
}

func (x *ReadProvaRequest) GetNomeProva() string {
	if x != nil {
		return x.NomeProva
	}
	return ""
}

func (x *ReadProvaRequest) GetIdUsuario() uint32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

type ReadAllProvaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdUsuario uint32 `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
}

func (x *ReadAllProvaRequest) Reset() {
	*x = ReadAllProvaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provas_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAllProvaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllProvaRequest) ProtoMessage() {}

func (x *ReadAllProvaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provas_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllProvaRequest.ProtoReflect.Descriptor instead.
func (*ReadAllProvaRequest) Descriptor() ([]byte, []int) {
	return file_provas_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllProvaRequest) GetIdUsuario() uint32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

type UpdateProvaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NovoNome  string                 `protobuf:"bytes,2,opt,name=novo_nome,json=novoNome,proto3" json:"novo_nome,omitempty"`
	NovaTurma string                 `protobuf:"bytes,3,opt,name=nova_turma,json=novaTurma,proto3" json:"nova_turma,omitempty"`
	DataProva *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=data_prova,json=dataProva,proto3" json:"data_prova,omitempty"`
}

func (x *UpdateProvaRequest) Reset() {
	*x = UpdateProvaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provas_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProvaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProvaRequest) ProtoMessage() {}

func (x *UpdateProvaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provas_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProvaRequest.ProtoReflect.Descriptor instead.
func (*UpdateProvaRequest) Descriptor() ([]byte, []int) {
	return file_provas_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProvaRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProvaRequest) GetNovoNome() string {
	if x != nil {
		return x.NovoNome
	}
	return ""
}

func (x *UpdateProvaRequest) GetNovaTurma() string {
	if x != nil {
		return x.NovaTurma
	}
	return ""
}

func (x *UpdateProvaRequest) GetDataProva() *timestamppb.Timestamp {
	if x != nil {
		return x.DataProva
	}
	return nil
}

type DeleteProvaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteProvaRequest) Reset() {
	*x = DeleteProvaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_provas_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProvaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProvaRequest) ProtoMessage() {}

func (x *DeleteProvaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provas_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProvaRequest.ProtoReflect.Descriptor instead.
func (*DeleteProvaRequest) Descriptor() ([]byte, []int) {
	return file_provas_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProvaRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_provas_proto protoreflect.FileDescriptor

var file_provas_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x75, 0x72, 0x6d, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x75, 0x72, 0x6d, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x12,
	0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x50,
	0x72, 0x6f, 0x76, 0x61, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x22,
	0x3d, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x12, 0x2f, 0x0a,
	0x0b, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f,
	0x76, 0x61, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x22, 0xb4,
	0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x6d, 0x65, 0x5f, 0x70, 0x72,
	0x6f, 0x76, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x6d, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x75, 0x72, 0x6d, 0x61, 0x5f, 0x70, 0x72,
	0x6f, 0x76, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x75, 0x72, 0x6d, 0x61,
	0x50, 0x72, 0x6f, 0x76, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61,
	0x50, 0x72, 0x6f, 0x76, 0x61, 0x22, 0x30, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x69, 0x64, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x22, 0x50, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x50,
	0x72, 0x6f, 0x76, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e,
	0x6f, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x6f, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64,
	0x5f, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x69, 0x64, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x22, 0x34, 0x0a, 0x13, 0x52, 0x65, 0x61,
	0x64, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x64, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x22,
	0x9b, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x76, 0x6f, 0x5f, 0x6e,
	0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x76, 0x6f, 0x4e,
	0x6f, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x76, 0x61, 0x5f, 0x74, 0x75, 0x72, 0x6d,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x76, 0x61, 0x54, 0x75, 0x72,
	0x6d, 0x61, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x22, 0x24, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x32, 0xbf, 0x02, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x52, 0x65, 0x61,
	0x64, 0x41, 0x6c, 0x6c, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f,
	0x76, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72,
	0x6f, 0x76, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x12,
	0x35, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f,
	0x2e, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x12, 0x3d, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x76, 0x61, 0x72, 0x6f, 0x6c, 0x75, 0x63, 0x69, 0x6f, 0x32,
	0x30, 0x30, 0x37, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x6f, 0x2d, 0x42, 0x44, 0x2d, 0x67,
	0x6f, 0x2d, 0x33, 0x2d, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_provas_proto_rawDescOnce sync.Once
	file_provas_proto_rawDescData = file_provas_proto_rawDesc
)

func file_provas_proto_rawDescGZIP() []byte {
	file_provas_proto_rawDescOnce.Do(func() {
		file_provas_proto_rawDescData = protoimpl.X.CompressGZIP(file_provas_proto_rawDescData)
	})
	return file_provas_proto_rawDescData
}

var file_provas_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_provas_proto_goTypes = []interface{}{
	(*Prova)(nil),                 // 0: projeto.Prova
	(*ProvaLista)(nil),            // 1: projeto.ProvaLista
	(*CreateProvaRequest)(nil),    // 2: projeto.CreateProvaRequest
	(*CreateProvaResponse)(nil),   // 3: projeto.CreateProvaResponse
	(*ReadProvaRequest)(nil),      // 4: projeto.ReadProvaRequest
	(*ReadAllProvaRequest)(nil),   // 5: projeto.ReadAllProvaRequest
	(*UpdateProvaRequest)(nil),    // 6: projeto.UpdateProvaRequest
	(*DeleteProvaRequest)(nil),    // 7: projeto.DeleteProvaRequest
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_provas_proto_depIdxs = []int32{
	8, // 0: projeto.Prova.data_prova:type_name -> google.protobuf.Timestamp
	0, // 1: projeto.ProvaLista.prova_lista:type_name -> projeto.Prova
	8, // 2: projeto.CreateProvaRequest.data_prova:type_name -> google.protobuf.Timestamp
	8, // 3: projeto.UpdateProvaRequest.data_prova:type_name -> google.protobuf.Timestamp
	2, // 4: projeto.ProvaService.Create:input_type -> projeto.CreateProvaRequest
	5, // 5: projeto.ProvaService.ReadAll:input_type -> projeto.ReadAllProvaRequest
	4, // 6: projeto.ProvaService.Read:input_type -> projeto.ReadProvaRequest
	6, // 7: projeto.ProvaService.Update:input_type -> projeto.UpdateProvaRequest
	7, // 8: projeto.ProvaService.Delete:input_type -> projeto.DeleteProvaRequest
	3, // 9: projeto.ProvaService.Create:output_type -> projeto.CreateProvaResponse
	1, // 10: projeto.ProvaService.ReadAll:output_type -> projeto.ProvaLista
	1, // 11: projeto.ProvaService.Read:output_type -> projeto.ProvaLista
	0, // 12: projeto.ProvaService.Update:output_type -> projeto.Prova
	9, // 13: projeto.ProvaService.Delete:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_provas_proto_init() }
func file_provas_proto_init() {
	if File_provas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_provas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prova); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvaLista); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provas_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProvaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provas_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProvaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provas_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadProvaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provas_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAllProvaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provas_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProvaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_provas_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProvaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_provas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provas_proto_goTypes,
		DependencyIndexes: file_provas_proto_depIdxs,
		MessageInfos:      file_provas_proto_msgTypes,
	}.Build()
	File_provas_proto = out.File
	file_provas_proto_rawDesc = nil
	file_provas_proto_goTypes = nil
	file_provas_proto_depIdxs = nil
}
