// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// UsuariosServiceClient is the client API for UsuariosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsuariosServiceClient interface {
	// Criar usuário
	Create(ctx context.Context, in *UsuarioCreateRequest, opts ...grpc.CallOption) (*Response, error)
	// Ler usuário
	Read(ctx context.Context, in *UsuarioReadRequest, opts ...grpc.CallOption) (*Usuario, error)
	// Atualizar usuário
	Update(ctx context.Context, in *UsuarioUpdateRequest, opts ...grpc.CallOption) (*Response, error)
	// Deletar usuário
	Delete(ctx context.Context, in *UsuarioDeleteRequest, opts ...grpc.CallOption) (*Response, error)
	// Minha vigarície...
	GivePassword(ctx context.Context, in *UsuarioGivePasswordRequest, opts ...grpc.CallOption) (*UsuarioGivePasswordResponse, error)
}

type usuariosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsuariosServiceClient(cc grpc.ClientConnInterface) UsuariosServiceClient {
	return &usuariosServiceClient{cc}
}

func (c *usuariosServiceClient) Create(ctx context.Context, in *UsuarioCreateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/projeto.UsuariosService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosServiceClient) Read(ctx context.Context, in *UsuarioReadRequest, opts ...grpc.CallOption) (*Usuario, error) {
	out := new(Usuario)
	err := c.cc.Invoke(ctx, "/projeto.UsuariosService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosServiceClient) Update(ctx context.Context, in *UsuarioUpdateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/projeto.UsuariosService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosServiceClient) Delete(ctx context.Context, in *UsuarioDeleteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/projeto.UsuariosService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosServiceClient) GivePassword(ctx context.Context, in *UsuarioGivePasswordRequest, opts ...grpc.CallOption) (*UsuarioGivePasswordResponse, error) {
	out := new(UsuarioGivePasswordResponse)
	err := c.cc.Invoke(ctx, "/projeto.UsuariosService/GivePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsuariosServiceServer is the server API for UsuariosService service.
// All implementations must embed UnimplementedUsuariosServiceServer
// for forward compatibility
type UsuariosServiceServer interface {
	// Criar usuário
	Create(context.Context, *UsuarioCreateRequest) (*Response, error)
	// Ler usuário
	Read(context.Context, *UsuarioReadRequest) (*Usuario, error)
	// Atualizar usuário
	Update(context.Context, *UsuarioUpdateRequest) (*Response, error)
	// Deletar usuário
	Delete(context.Context, *UsuarioDeleteRequest) (*Response, error)
	// Minha vigarície...
	GivePassword(context.Context, *UsuarioGivePasswordRequest) (*UsuarioGivePasswordResponse, error)
	mustEmbedUnimplementedUsuariosServiceServer()
}

// UnimplementedUsuariosServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUsuariosServiceServer struct {
}

func (UnimplementedUsuariosServiceServer) Create(context.Context, *UsuarioCreateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUsuariosServiceServer) Read(context.Context, *UsuarioReadRequest) (*Usuario, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedUsuariosServiceServer) Update(context.Context, *UsuarioUpdateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUsuariosServiceServer) Delete(context.Context, *UsuarioDeleteRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUsuariosServiceServer) GivePassword(context.Context, *UsuarioGivePasswordRequest) (*UsuarioGivePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GivePassword not implemented")
}
func (UnimplementedUsuariosServiceServer) mustEmbedUnimplementedUsuariosServiceServer() {}

// UnsafeUsuariosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsuariosServiceServer will
// result in compilation errors.
type UnsafeUsuariosServiceServer interface {
	mustEmbedUnimplementedUsuariosServiceServer()
}

func RegisterUsuariosServiceServer(s *grpc.Server, srv UsuariosServiceServer) {
	s.RegisterService(&_UsuariosService_serviceDesc, srv)
}

func _UsuariosService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.UsuariosService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).Create(ctx, req.(*UsuarioCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsuariosService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.UsuariosService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).Read(ctx, req.(*UsuarioReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsuariosService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.UsuariosService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).Update(ctx, req.(*UsuarioUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsuariosService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.UsuariosService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).Delete(ctx, req.(*UsuarioDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsuariosService_GivePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsuarioGivePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServiceServer).GivePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projeto.UsuariosService/GivePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServiceServer).GivePassword(ctx, req.(*UsuarioGivePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsuariosService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projeto.UsuariosService",
	HandlerType: (*UsuariosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UsuariosService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _UsuariosService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UsuariosService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UsuariosService_Delete_Handler,
		},
		{
			MethodName: "GivePassword",
			Handler:    _UsuariosService_GivePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usuarios.proto",
}
